[Arquivos Template][Cria template de projeto]
betrybe/sd-0x-project-trybewarts pull request #1
Opened 2021-03-09 20:21 UTC by BrunoPDRS

Realiza criação dos arquivos de template do projeto Trybewarts.

Repositório de staging: https://github.com/betrybe/sd-0x-project-trybewarts-rubric
PR testando o funcionamento do avaliador automático: https://github.com/betrybe/sd-0x-project-trybewarts-rubric/pull/5

Repositório de testes: https://github.com/betrybe/sd-0x-project-trybewarts-tests
PR com a branch utilizada nos testes em staging: https://github.com/betrybe/sd-0x-project-trybewarts-tests/pull/1

2021-03-10 11:18 UTC, cleytonoliveira commented on .trybe/requirements.json
> +      "description": "2 - A barra superior deve conter o logotipo do Trybewarts no canto esquerdo com a classe trybewarts-header-logo",
```suggestion
      "description": "2 - Adicione uma barra superior contendo o logotipo do Trybewarts no canto esquerdo com a classe trybewarts-header-logo",
```
Penso que seria interessante um comando mais direto. Analisem se faz sentido.

2021-03-10 11:28 UTC, cleytonoliveira commented on .trybe/requirements.json
> +      "description": "3 - A barra superior deve conter um formulário de autenticação no canto direito com um input de login, um de senha e um botão de entrar",
```suggestion
      "description": "3 - Acrescente um formulário de autenticação no canto direito da barra superior contendo os inputs de login, de senha e um botão de entrar",
```
Mesmo situação do anterior. Coloquei neste formato, mas ainda não fiquei contente com ele rsrs, vejam o que acham.

2021-03-10 11:30 UTC, cleytonoliveira commented on .trybe/requirements.json
> +      "description": "8 - No formulário, crie inputs de 'Nome:', 'Sobrenome:' e 'Email'",
```suggestion
      "description": "8 - Acrescente no formulário os inputs de 'Nome:', 'Sobrenome:' e 'Email'",
```

2021-03-10 13:31 UTC, LucasSGomide requested changes
Parabéns pelo trabalho galera !
O ponto que comentei sobre "O que será verificado" vai dar um trabalho a mais, talvez não seja possível implementar em cima da hora, ai qualquer coisa marquem como resolvido e arrumamos isto para as próximas turmas, se não for um problema.
:rocket:

2021-03-10 13:56 UTC, phelipe-ohlsen commented on README.md
> +- [ESLint](#eslint)
Esse tópico referente ao **ESlint** está fora do lugar, atualmente é inserido dentro do **Como desenvolver**.

2021-03-11 13:41 UTC, sdayube commented on .trybe/requirements.json
> +      "description": "2 - A barra superior deve conter o logotipo do Trybewarts no canto esquerdo com a classe trybewarts-header-logo",
Bom, se a questão é a imperatividade do comando acho que faz mais sentido ficar assim:

```suggestion
      "description": "2 - Adicione o logotipo da Trybewarts com a classe "trybewarts-header-logo" no canto esquerdo da barra superior,
```

Digo isso porque no 1 a gente já manda a pessoa criar a barra.

2021-03-16 23:25 UTC, roziscoding commented on .eslintrc.json
> +    "extends": ["airbnb-base", "plugin:cypress/recommended", "trybe-fundamentals"],
Por que não estamos extendendo só o `trybe-fundamentals` aqui?

2021-03-16 23:25 UTC, roziscoding commented on .github/workflows/main.yml
> +  evaluator_job:
Se entendi direito, está faltando a dependência entre os jobs, não?
O evaluator, por exemplo, só deveria rodar caso o ESLint passe, correto?

2021-03-16 23:51 UTC, BrunoPDRS commented on .github/workflows/main.yml
> +  evaluator_job:
O Batista comentou sobre uma possível discussão se este projeto tem a intenção de cobrar os fixes do style/eslint, por isso não colocamos. Você acha que seria interessante acrescentar essa dependência? É coisa rápida de resolver, caso sim (:

2021-03-16 23:52 UTC, BrunoPDRS commented on .eslintrc.json
> +    "extends": ["airbnb-base", "plugin:cypress/recommended", "trybe-fundamentals"],
Boa pergunta, só adicionamos à lista que já existia. Mas faz sentido deixar apenas o trybe-fundamentals

2021-03-17 12:28 UTC, BrunoPDRS commented on .eslintrc.json
> +    "extends": ["airbnb-base", "plugin:cypress/recommended", "trybe-fundamentals"],
Extensão do trybe-fundamentals agora é a única requisitada

2021-03-17 12:29 UTC, BrunoPDRS commented on .github/workflows/main.yml
> +  evaluator_job:
Dependência dos steps feitas e o step do ESLint foi criado

2021-03-18 16:19 UTC, albertosca reviewed
Projeto **sensacional, galera!** Muito, muito bom! Só anotei uns pontos:

- Rola de padronizar o nome dos SVGs? Sem a maiúscula no começo deles, tipo. Pra ser um `snake-case` certinho.
- Eu senti falta de mais localizadores espaciais pra estressar Flexbox... Tipo: Textarea tem que ficar embaixo do campo nome, o seletor de casa embaixo a logo à direita, essas coisas! O que vcs acham? Fiquei na dúvida de estarmos cobrando muito pouco, ou só coisas mais simples, tipo 2-3 elementos se posicionarem, e não partes maiores do forms também.
- Vamo cobrar media query! Marreta o tamanho da tela pra ficar pequena aqui no Cypress e checa que o layout do formulário mudou de algum jeito específico! Acho importante ter algo obrigatório sobre isso 🤔 

O que vcs acham? Só não cheguei a rodar o projeto e os testes mesmo, então é importante os nossos testes aqui serem bem robustos =) 

Qualquer coisa to à disposição!

2021-03-18 16:19 UTC, albertosca commented on README.md
> +⚠ **Alguns requisitos pedem para utilizar flexbox. Tenha atenção no que é solicitado caso vá usar algum framework CSS para que os requisitos sejam atendidos.** ⚠
```suggestion
⚠ **Alguns requisitos pedem para utilizar Flexbox. Tenha atenção no que é solicitado caso vá usar algum framework CSS para que os requisitos sejam atendidos.** ⚠
```

2021-03-18 16:19 UTC, albertosca commented on README.md
> +## ESLint
Essa seção, junto com a próxima, ficaram meio confusas por estarem separadas e um pouco diferentes do normal. Vale juntar as duas e colocar o alerta ao final, não?

Ah! [Esse link](https://app.betrybe.com/course/real-life-engineer/eslint) pode entrar aqui também! Nossa novíssima página que explica o que é ESLint pro pessoal. Acho legal ter isso aqui, hein! 👌

2021-03-18 16:19 UTC, albertosca commented on README.md
> +### 23. Realize o desenvolvimento da versão mobile do formulário Trybewarts.
Vale detalhar um tico esses requisitos, hein? E marcar eles (tanto no índice quando numa seção separada aqui) como **Requisitos não avaliativos**, que não contam com nota.

Ah. O feedback será **apresentado?** Isso vai prejudicar o recebimento dos feedbacks, não? 🤔 
cc @antoniosb O que vc acha aqui? 🚀

2021-03-18 16:19 UTC, albertosca commented on cypress/integration/project.spec.js
> +        .should('have.css', 'flex-direction', 'row');
Não daria pra gente usar os "localizadores espaciais" de requisitos aqui não? Tipo, pra gente garantir que um tá do lado do outro e que nenhum tá em cima do outro? Sem forçar o uso de um estilo específico? Penso nisso muito porque espiar esse teste praticamente dá a resposta do requisito, né 😬 

Mas pode ser que seja muito trabalhoso fazer isso. Acho válido avaliar se dá, mas se não der beleza.

2021-03-18 16:19 UTC, albertosca commented on cypress/integration/project.spec.js
> +    it('O campo `textarea` deverá ter o máximo de 500 caracteres', () => {
A pessoa pode fazer isso de outras formas, sem usar esse atributo. Que tal desengessar um pouco? Podemos digitar 501 caracteres aqui e conferir que só há 500 no campo! Ai independente da regra o requisito vai estar verificado!

2021-03-18 16:19 UTC, albertosca commented on cypress/integration/project.spec.js
> +      cy.get(`${TRYBEWARTS_LOGIN_FORM_SELECTOR} input:nth-child(1)`).type('tryber@betrybe.com');
```suggestion
      cy.get(`${TRYBEWARTS_LOGIN_FORM_SELECTOR} input:nth-child(1)`).type('tryber@teste.com');
```

Melhor usar um email que com certeza nunca vai existir, just in case 😂

2021-03-19 12:09 UTC, sdayube commented on README.md
> +### 23. Realize o desenvolvimento da versão mobile do formulário Trybewarts.
Rapaz, quanto ao feedback ser apresentado me parece que foi um typo mesmo 😅. O que vai ser efetivamente apresentado é a versão mobile, assim com era no projeto do Facebook (a não ser que vocês realmente queiram que os alunos apresentem isso também, mas não me parece ser o caso). Já estamos corrigindo!

2021-03-22 12:08 UTC, cleytonoliveira approved these changes

2021-03-22 12:25 UTC, LucasSGomide approved these changes

2021-03-22 13:36 UTC, albertosca commented on README.md
> +  ### 23. Preencha o arquivo feedback.md . Aproveite o espaço para deixar seus feedbacks sobre o projeto.
@Tem que ajustar a formatação aqui!

2021-03-22 14:33 UTC, albertosca commented on README.md
> +    - [21. Faça com que ao clicar no botão 'Enviar', o conteúdo do formulário seja substituído pelas informações preenchidas](#21-faça-com-que-ao-clicar-no-botão-enviar-o-conteúdo-do-formulário-seja-
Tem que marcar abaixo disso como `Lista de requisitos não avaliativos:`!

2021-03-22 14:36 UTC, albertosca commented on README.md
> +Esses requisitos **não** são verificáveis pelo avaliador automático. A apresentação **(opcional)** do requisito 22 será realizada durante o fechamento do dia seguinte ao final do projeto
A gente *garante* isso pra todas as turmas, a apresentação? E se alguma não quiser, tipo? Acho melhor não ter essa promessa... Não? 🤔

2021-03-22 14:36 UTC, NatanaelNeto commented on README.md
> +    - [21. Faça com que ao clicar no botão 'Enviar', o conteúdo do formulário seja substituído pelas informações preenchidas](#21-faça-com-que-ao-clicar-no-botão-enviar-o-conteúdo-do-formulário-seja-
Resolvido, PR subindo! 👍

2021-03-22 14:37 UTC, albertosca approved these changes

2021-03-22 14:38 UTC, NatanaelNeto commented on README.md
> +Esses requisitos **não** são verificáveis pelo avaliador automático. A apresentação **(opcional)** do requisito 22 será realizada durante o fechamento do dia seguinte ao final do projeto
Pode ser, vou atualizar aqui.

2021-03-22 14:57 UTC, merged